### ISSUE TITLE
Stupid question... :-)

### ISSUE THREAD

**Issue by philippe-toussaint** [aniou/go65c816#3]
Does the emulator supports loading programs ? If so, is there some examples ? How to do that ?

**Comment by aniou** [comment]
Sorry, for delayed response. That version of emulator supports loading files by editing files in ``conf/`` directory, for example, in section [cpu0] there are file1, file2, file3 etc. that are loaded in order. Currently supported format is intel hex, that may be inconvenient for motorola users.

Currently, my main efforts are concentrated on new version of emulator: https://github.com/aniou/morfeo that initially was focused on a2560x machine but slowly gains support for 65c02/65c816 cpus. In that case files ale loaded from command-line, but still required format is intel hex. To be improved in future.

```
$ cat conf/a2560k.ini

[platform]
mode=a2560k-like
DIP6=on
scale=2
disk0=data/test-fat32.img

[cpu0]
file1=data/foenixmcp.hex
file2=data/foenix-st_8x8.hex
file3=data/foenix-st_8x8-channelb.hex

[cpu1]
enable=0
```
