### ISSUE TITLE
Small stack bug in 65816 emulation mode

### ISSUE THREAD

**Issue by mgcaret** [aniou/go65c816#5]
https://github.com/aniou/morfe/blob/master/emulator/cpu_65c816/cpu.go#L689

https://github.com/aniou/morfe/blob/master/emulator/cpu_65c816/cpu.go#L699

In both of those lines, the 0x1000 should be 0x100.

**Comment by aniou** [comment]
What a silly mistake! Thank You and sorry for delayed response - in last years  I was focused on better implementation of 65xx family, built upon common foundations. Currently active development has place in https://github.com/aniou/morfeo/tree/master/emulator/cpu but machines itself are restricted to barebones, sufficient for running tests.

**Comment by mgcaret** [comment]
No worries, I adopted your core for automated testing of OF816 and that cropped up when executing my monitor program. I checked out the new project, I have never looked at Odin before, looks neat.
